### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sheim** [brandonjdehart/gloptipoly3-pod#1]
Hi, sorry I'm doing this through an 'issue', still getting the hang of github and didn't find other ways to contact...
Are you planning on integrating glopt into Drake, i.e. is this the purpose of this wrapper?

**Comment by brandonjdehart** [comment]
Yes. I've been working with Drake but I'm not part of the RobotLocomotion group, so some of their submodules are inaccessible to me. I figured other people might have the same issues, so I've uploaded my initial attempts at building wrappers for gloptipoly, sedumi, and studentsnopt.

I will be baking my own version of drake-distro soon as well which will include these submodules, so that new users can just clone the whole shebang and be off to the races.

**Comment by sheim** [comment]
Awesome, I heard of glopt was a good alternative to snopt, looking forward to it.

**Comment by brandonjdehart** [comment]
If you're wanting to use glopt now, all you need to do is clone this repo into your drake-distro folder and add a 'gloptipoly3' line to the tobuild.txt file. If you run make once you've done that, then drake should be able to use glopt.

I haven't done much testing so I can't guarantee it will work as expected, as I typically use snopt, but if you're willing to test it I'm 100% in favour.

**Comment by sheim** [comment]
Will do, it was on my to-do-list already, but have a couple of deadlines
coming up : ). I'll let you know as I run into things.

On Fri, Feb 27, 2015 at 12:34 AM, Brandon J DeHart <notifications@github.com
