### ISSUE TITLE
Missing Sedumi dependency

### ISSUE THREAD

**Issue by sheim** [brandonjdehart/gloptipoly3-pod#2]
Gloptpoly3 requires a solver, the default being Sedumi, but if this is missing it doesn't complain (which I think it should).

I'm not so familiar with makefiles yet, but if you're not in a rush I'll try to fix this soon-ish.

Note 1: I installed Sedumi manually for now, and gloptpoly works (at least their demo).
Note 2: I couldn't make your fork of drake-distro, and there is also no button for opening new issues on it (not sure if that is intentional or not). I ran this on the official drake-distro, using the rigidbody distro.

**Comment by brandonjdehart** [comment]
Happy to hear that it works once you've got sedumi installed. Since you can use a variety of solvers with glopt, I might just leave it as is. If it's checking specifically for sedumi and someone wants to use something else, then it will just throw errors/warnings for no reason.

As far as my drake-distro goes, I have yet to actually upload my local changes so the fork is just a snapshot of the original drake-distro right now. I would assume that once I've made changes to my fork then there will be an issues button. Once I do upload my local changes, you should be able to use the master branch of my fork instead of the rigidbody branch of the original repo (which is one of the reasons I forked it in the first place).

**Comment by brandonjdehart** [comment]
Update on the status of my drake-distro: I've uploaded my local changes to the "mymaster" branch of my drake-distro fork. You should be able to clone the repo and its submodules and start using drake with snopt, glopt, and sedumi out of the box.

**Comment by sheim** [comment]
Done! Everything works out except gurobi, something with the perl-script for downloading. When I try to compile that, after asking for e-mail and password, it gives this error:
Can't call method "value" on an undefined value at ./download_gurobi.pl line 33, <> line 2.
make: **\* [gurobi562] Error 255

I'm not using gurobi, so I just took it off the tobuild list, everything else works like a charm : ). Oh and, there's still no "issues" button on your drake-distro : )

**Comment by brandonjdehart** [comment]
I think I had the gurobi issue myself, then read through the drake-distro installation guide and realized that I needed to rerun the install_prereqs script after switching branches from rigidbody to master. Since gurobi uses some extra libraries that the rest of the distro does not, you need to make sure to install its prerequisites as well. I think if you do that, then gurobi should work fine, as I haven't messed with the gurobi submodule at all.

Found an option in the drake-distro fork to enable issues, so there's a button now. :)

**Comment by brandonjdehart** [comment]
Just an FYI, apparently the Gurobi website has changed, so until the download script in the gurobi pod gets fixed, the easiest way to use gurobi is just to download it directly. In case you're planning on playing with it anytime soon.

**Comment by brandonjdehart** [comment]
Update: Gurobi pod has been updated in the source repo, and I've update the reference in mine. Should work fine now. I'm going to close this issue, but feel free to start a new one if there is anything else.
